---
title: "Graded_lab(dplyr_tidyr)"
author: "Kenza Redwane"
format: 
  html:
    code-fold: true
---

## Exercice 1

```{r}
#| message: false
#| cache: false
here::i_am("top-spotify-songs-from-20102019-by-year.csv")
library(here)
library(dplyr)
library(tidyr)
```
### Question 1: Load data
```{r}
library(readr)
spotify <- read_delim("/Users/macbookpro/Desktop/Master/Semester One/Data Management and Programming/dplyr_tidyr-graded.lab-/top-spotify-songs-from-20102019-by-year.csv",";")

```

### Question 2: Using distinct (among other functions) compute the number of different songs, artists and musical genre that have been included in the data set.
```{r}
spotify %>% distinct(song_name, artist, genre)

```

### Question 3:
```{r}

```

### Question 4:
```{r}

```

### Question 5:
```{r}

```

## Exercice 2

### Question 1:
```{r}

```

### Question 2:
```{r}

```

### Question 3:
```{r}

```

### Question 4:
```{r}

```

### Question 5:
```{r}

```

### Question 6:
```{r}

```

### Question 7:
```{r}

```

### Question 8:
```{r}

```

### Question 9:
```{r}

```

### Question 10:
```{r}

```

### Question 11:
```{r}

```